<link rel="stylesheet" href="/articles/designing-joy/article_style.css" />
<title>Designing Joy</title>
<meta name="description" content="Case study of the 2018 Crèche Exhibit foyer design made primarily in laser cut cardboard." />
<meta name="keywords" content="christmas, creche, cardboard, laser cut, star, lattice, joy" />
<meta property="og:image" content="http://blog.andygriff.in/articles/designing-joy/imgs/article_og.jpg">